### ISSUE TITLE
Not Running

### ISSUE THREAD

**Issue by lazyCoder-max** [Arada-Software-Technologies/TelegramBotProject1#8]
hay Emanuel,
before shooting my comments to you I would like to tell you that I loved the way you write your code. and I admire your great job (you put the bot **username** that helped me to find the bot and the comments helped me to understand everything without reading the code). but here is the issue that I found when I tried to run the program.
as you can see on the BotCode_branch you created multiple classes. because of that reason, the program won't be able to run. It will throw an error message.
Please fix this issue and make sure that you pushed (merged) the stable version of your branch on the codebase (master branch)
**Salute**

**Comment by Leunama-g** [comment]
it doesnt show any errors on my end can you maybe tell me what the error is so that i can fix it

**Comment by lazyCoder-max** [comment]
> it doesnt show any errors on my end can you maybe tell me what the error is so that i can fix it

I think it is now resolved and i found another error. i attached a screenshot of the issue.
![issue](https://user-images.githubusercontent.com/51710331/103073804-4f902a80-45d9-11eb-8053-ba91469d1498.JPG)

**Comment by Leunama-g** [comment]
i updated the bot code branch... i think it's fixed now

**Comment by Leunama-g** [comment]
the game is pretty much done just the database that holds the highscore board is left... is the bug fixed now?... i just tested the bot code branch before pushing it and it works fine on my end

**Comment by Leunama-g** [comment]
The bot is fully done now i have merged all of the branches to the master.
i just pulled the master branch and tested it and everything is working as expected

**Comment by lazyCoder-max** [comment]
> The bot is fully done now i have merged all of the branches to the master.
> i just pulled the master branch and tested it and everything is working as expected

Great!
I will look into it...
